application: miniedenalpha
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /lib
  static_dir: lib
  application_readable: true
- url: /css
  static_dir: css
  application_readable: true
#- url: /main.js
#  mime_type: text/javascript
#  static_files: main.js
#  upload: main.js
#- url: /.*
#  mime_type: text/html
#  static_files: index.html
#  upload: index.html
- url: /.*
  script: main.app
  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest